# Disable some built-in rules
config:
  no-trailing-spaces: false
  no-multiple-blanks: false
  # See https://github.com/DavidAnson/markdownlint/blob/v0.32.1/README.md#rules--aliases
  MD004: false
  MD013: false
  MD024: false
  MD033: false
  MD036: false
  MD042: false
  MD045: false

# Fix any fixable errors
fix: true

# Ignore files referenced by .gitignore (only valid at root)
gitignore: true

ignores:
  - docs/other-templates/*

# Disable banner message on stdout (only valid at root)
noBanner: true

# Disable inline config comments
noInlineConfig: true

# Disable progress on stdout (only valid at root)
noProgress: true

# Show found files on stdout (only valid at root)
showFound: true
